// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ytchop} from '../models';
import {ytchat} from '../models';

export function Download(arg1:string,arg2:Array<ytchop.ChopData>):Promise<string>;

export function GetChatCount(arg1:string):Promise<Array<ytchat.CountData>>;

export function Greet(arg1:string):Promise<string>;
